name: flutter_kundol
description: A new Flutter ecommerce application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">2.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^7.3.3
  equatable: ^2.0.0
  shared_preferences: ^2.0.5
  carousel_slider: ^4.1.1
  dio: ^5.4.0
  cached_network_image: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_sliders: ^21.1.41
  range_slider_flutter: ^0.0.2
  flutter_range_slider_ns: ^0.0.2
  #  flutter_range_slider: ^1.5.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.0
  flutter_login_facebook: ^1.0.1
  share: ^2.0.4
  intl_phone_number_input:
  in_app_review: ^2.0.2
  onesignal_flutter: ^5.0.4
  flutter_svg: ^ 1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  launch_review: ^3.0.1
  dropdown_search: ^5.0.6
  google_maps_place_picker_mb: ^3.0.2
  google_maps_flutter: ^2.1.12
  bubble_tab_indicator: ^0.1.6
  webview_flutter: ^2.0.4
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  toggle_switch: ^2.1.0
  chewie: ^1.5.0
  flutter_math_fork: ^0.6.0
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.1.0
  pinput: ^3.0.1
  google_nav_bar: ^5.0.6
  im_stepper: ^1.0.1+1
  smooth_star_rating_null_safety: ^1.0.4+2
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  #  flutter_layout_grid: ^1.0.0
  intl:
  razorpay_flutter: ^1.3.6
  image_picker: ^1.0.7
#  multi_image_picker: ^4.8.01
  path_provider: ^2.0.1
  multi_image_picker_plus: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon/Logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/images/
    - assets/icons/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #-Xmx1536M graddle properties changes --org.gradle.jvmargs=-XX:MaxHeapSize=256m -Xmx256m
